In [63]:
import matplotlib.pyplot as plt
import numpy as np
import os
import random

In [64]:
data_path = 'languageID'
alpha = 1/2 
K_l = 3
num_sample = {'e': 10, 's': 10, 'j' : 10}
prior = {}
for label in num_sample:
    cnt = num_sample[label]
    prior[label] = (cnt + alpha)/ (sum(num_sample.values()) + (K_l*alpha))
prior

{'e': 0.3333333333333333, 's': 0.3333333333333333, 'j': 0.3333333333333333}

In [65]:
lang = []
dict_list = []
for label in ['e','s','j']:
    alpha_cnt = {}
    for i in range (0, 10):
        name = label + (str(i)) + ".txt"
        file_path = os.path.join('languageID', name)
        with open(file_path,'r') as f:
            content = f.read()
            for char in content:
                if char.isalpha() or char.isspace():
                    if char in alpha_cnt:
                        alpha_cnt[char] += 1
                    else:
                        alpha_cnt[char] = 1
    #sort keys
    if '\n' in alpha_cnt:
        del alpha_cnt['\n']

    sorted_dict = {key: alpha_cnt[key] for key in sorted(alpha_cnt.keys())}
    #finding theta
    deno = sum(sorted_dict.values()) + alpha*len(sorted_dict)
    theta = []
    for val in sorted_dict:
        i = (sorted_dict[val] + alpha)/ deno
        theta.append(i)
    dict_list.append(sorted_dict)
    lang.append(theta)


In [66]:
dict_list[2]

{' ': 1766,
 'a': 1885,
 'b': 155,
 'c': 78,
 'd': 246,
 'e': 861,
 'f': 55,
 'g': 200,
 'h': 454,
 'i': 1388,
 'j': 33,
 'k': 821,
 'l': 20,
 'm': 569,
 'n': 811,
 'o': 1304,
 'p': 12,
 'q': 1,
 'r': 612,
 's': 603,
 't': 815,
 'u': 1010,
 'v': 3,
 'w': 282,
 'y': 202,
 'z': 110}

In [67]:
lang[0]

[0.1792499586981662,
 0.0601685114819098,
 0.011134974392863043,
 0.021509995043779945,
 0.021972575582355856,
 0.1053692383941847,
 0.018932760614571286,
 0.017478936064761277,
 0.047216256401784236,
 0.055410540227986124,
 0.001420783082768875,
 0.0037336857756484387,
 0.028977366595076822,
 0.020518751032545846,
 0.057921691723112505,
 0.06446390219725756,
 0.01675202378985627,
 0.0005617049396993227,
 0.053824549810011564,
 0.06618205848339666,
 0.08012555757475633,
 0.026664463902197257,
 0.009284652238559392,
 0.015496448042293078,
 0.001156451346439782,
 0.013844374690236246,
 0.0006277878737815959]

In [68]:
#s
lang[1]

[0.16826493170115014,
 0.10456045141993771,
 0.008232863618143134,
 0.03752582405722919,
 0.039745922111559924,
 0.1138108599796491,
 0.00860287996053159,
 0.0071844839813758445,
 0.0045327001942585795,
 0.049859702136844375,
 0.006629459467793161,
 0.0002775122567913416,
 0.052943171656748174,
 0.02580863988159477,
 0.054176559464709693,
 0.07249236841293824,
 0.02426690512164287,
 0.007677839104560451,
 0.05929511886774999,
 0.06577040485954797,
 0.03561407295488884,
 0.03370232185254849,
 0.00588942678301625,
 9.250408559711388e-05,
 0.0024976103111220747,
 0.007862847275754679,
 0.0026826184823163022]

In [69]:
#j
lang[2]

[0.12345377035432245,
 0.13177021455028304,
 0.010867286323293032,
 0.005486057725906772,
 0.01722692012020407,
 0.06020686281361381,
 0.003878677755258928,
 0.014012160178908379,
 0.031763225941715004,
 0.09703682996715354,
 0.002341183870291425,
 0.05741141938640017,
 0.0014326647564469914,
 0.039800125794954226,
 0.05671255852959676,
 0.09116639877000489,
 0.0008735760710042631,
 0.00010482912852051157,
 0.04280522747920889,
 0.042176252708085823,
 0.05699210287231812,
 0.07061988957998462,
 0.00024460129988119366,
 0.019742819204696345,
 0.014151932350269061,
 0.007722412467677685]

In [70]:
#2.4
alpha_cnt = {}
name = 'e10.txt'
file_path = os.path.join('languageID', name)
with open(file_path,'r') as f:
    content = f.read()
    for char in content:
        if char.isalpha() or char.isspace():
            if char in alpha_cnt:
                alpha_cnt[char] += 1
            else:
                alpha_cnt[char] = 1
#sort keys
if '\n' in alpha_cnt:
    del alpha_cnt['\n']

x_test = {key: alpha_cnt[key] for key in sorted(alpha_cnt.keys())}
#finding theta
deno = sum(x_test.values()) + alpha*len(x_test)
theta_test = []
for val in x_test:
    i = (x_test[val] + alpha)/ deno
    theta_test.append(i)


In [71]:
x_test

{' ': 498,
 'a': 164,
 'b': 32,
 'c': 53,
 'd': 57,
 'e': 311,
 'f': 55,
 'g': 51,
 'h': 140,
 'i': 140,
 'j': 3,
 'k': 6,
 'l': 85,
 'm': 64,
 'n': 139,
 'o': 182,
 'p': 53,
 'q': 3,
 'r': 141,
 's': 186,
 't': 225,
 'u': 65,
 'v': 31,
 'w': 47,
 'x': 4,
 'y': 38,
 'z': 2}

In [72]:
#log likelihood
p_list = []
language = 0
for label in ['e', 's', 'j']:
    i = 0
    p = 0
    for x in x_test:
        if x == list(dict_list[language].keys())[i]:
            p = p + x_test[x]*np.log(lang[language][i])
            i = i + 1
    p_list.append(p) 
    language = language + 1
p_list


[-7841.865447060634, -8467.282044010557, -8730.288949147405]

In [73]:
label_list = ['e', 's', 'j'] 
#log likelihood
p_list = []
language = 0
for label in ['e', 's', 'j']:
    i = 0
    p = 0
    for x in x_test:
        if x == list(dict_list[language].keys())[i]:
            p = p + x_test[x]*np.log(lang[language][i])
            i = i + 1
    p_list.append(p) 
    language = language + 1
p_list

#log posterior
p_list_post = p_list + np.log(list(prior.values()))
 
#show the class label (Choose the class with the highest posterior probability as the predicted class label for x)
ind_max = np.argmax(p_list_post)
label_list[ind_max]

'e'

In [74]:
#test files 10.txt to 19.txt in three languages
ee, ss, jj, ej, es, js, je, se, sj = 0,0,0,0,0,0,0,0,0
for label in ['e', 's', 'j']:
    for i in range(10, 20):
        alpha_cnt = {}
        name = label + str(i) + '.txt'
        file_path = os.path.join('languageID', name)
        with open(file_path,'r') as f:
            content = f.read()
            for char in content:
                if char.isalpha() or char.isspace():
                    if char in alpha_cnt:
                        alpha_cnt[char] += 1
                    else:
                        alpha_cnt[char] = 1
        #sort keys
        if '\n' in alpha_cnt:
            del alpha_cnt['\n']

        x_test = {key: alpha_cnt[key] for key in sorted(alpha_cnt.keys())}
        #finding theta
        deno = sum(x_test.values()) + alpha*len(x_test)
        theta_test = []
        for val in x_test:
            i = (x_test[val] + alpha)/ deno
            theta_test.append(i)
        
        #log likelihood
        p_list = []
        language = 0
        for label2 in ['e', 's', 'j']:
            i = 0
            p = 0
            for x in x_test:
                if x == list(dict_list[language].keys())[i]:
                    p = p + x_test[x]*np.log(lang[language][i])
                    i = i + 1
            p_list.append(p) 
            language = language + 1
        
        #log posterior
        p_list_post = p_list + np.log(list(prior.values()))

        #show the class label (Choose the class with the highest posterior probability as the predicted class label for x)
        ind_max = np.argmax(p_list_post)
        clas = label_list[ind_max]
        #evaluate
        if label == 'e' and clas == 'e':
            ee += 1
        if label == 'e' and clas == 'j':
            ej += 1
        if label == 'e' and clas == 's':
            es += 1
        if label == 'j' and clas == 'j':
            jj += 1
        if label == 'j' and clas == 's':
            js += 1
        if label == 'j' and clas == 'e':
            je += 1
        if label == 's' and clas == 's':
            ss += 1
        if label == 's' and clas == 'j':
            sj += 1
        if label == 's' and clas == 'e':
            se += 1
print(ee, ss, jj, ej, es, js, je, se, sj)

10 10 10 0 0 0 0 0 0


In [75]:
#2.8
alpha_cnt = {}
name = 'e10.txt'
file_path = os.path.join('languageID', name)
with open(file_path,'r') as f:
    content = f.read()
    shuffled_content = ''.join(random.sample(content, len(content)))
    for char in content:
        if char.isalpha() or char.isspace():
            if char in alpha_cnt:
                alpha_cnt[char] += 1
            else:
                alpha_cnt[char] = 1
#sort keys
if '\n' in alpha_cnt:
    del alpha_cnt['\n']

x_test = {key: alpha_cnt[key] for key in sorted(alpha_cnt.keys())}
#finding theta
deno = sum(x_test.values()) + alpha*len(x_test)
theta_test = []
for val in x_test:
    i = (x_test[val] + alpha)/ deno
    theta_test.append(i)
x_test


{' ': 498,
 'a': 164,
 'b': 32,
 'c': 53,
 'd': 57,
 'e': 311,
 'f': 55,
 'g': 51,
 'h': 140,
 'i': 140,
 'j': 3,
 'k': 6,
 'l': 85,
 'm': 64,
 'n': 139,
 'o': 182,
 'p': 53,
 'q': 3,
 'r': 141,
 's': 186,
 't': 225,
 'u': 65,
 'v': 31,
 'w': 47,
 'x': 4,
 'y': 38,
 'z': 2}

# Neural Networks 

In [101]:
# https://nextjournal.com/gkoehler/pytorch-mnist
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import numpy as np
import torch.nn as nn
import matplotlib.pyplot as plt
#criterion is a PyTorch loss function that computes the loss between the predicted output 
criterion = nn.CrossEntropyLoss()

In [106]:
#Define hyperparemeters
batch_size = 32
batch_size_test = 10
learning_rate = 0.01
num_epochs = 20
input_size = 784  #28x28 pixels
hidden_size1 = 300
hidden_size2 = 200
num_classes = 10

In [107]:
#Load the MNIST dataset 
#TorchVision also offers a lot of handy transformations, such as cropping or normalization.
train_dataset = datasets.MNIST(root= './data', train= True, transform= transforms.ToTensor(), download= True)
test_dataset = datasets.MNIST(root = './data', train = False, transform= transforms.ToTensor())

In [108]:
#Create data loaders
train_loader = DataLoader(dataset= train_dataset, batch_size= batch_size, shuffle= True)
test_loader = DataLoader(dataset= test_dataset, batch_size= batch_size_test, shuffle=False)

In [109]:
#define the model
#The torch.randn function generates a tensor of size (hidden_size1, input_size) 
#filled with random values drawn from a normal distribution with mean 0 and standard deviation 1
#The division by np.sqrt(input_size) scales the initial weights by the square root of the input size, 
#which is a common practice to ensure that the initial weights are not too large or too small.
W1 = torch.randn(hidden_size1, input_size) / np.sqrt(input_size)
W2 = torch.randn(hidden_size2, hidden_size1) / np.sqrt(hidden_size1)
W3 = torch.randn(num_classes, hidden_size2) / np.sqrt(hidden_size2)

In [110]:
def forward(x):
    z1 = torch.matmul(W1, x)
    a1 = torch.sigmoid(z1)
    z2 = torch.matmul(W2, a1)
    a2 = torch.sigmoid(z2)
    z3 = torch.matmul(W3, a2)
    y_hat = torch.softmax(z3, dim = 0)
    return a1, a2, y_hat    

In [111]:
y = np.zeros((num_classes, batch_size))
y.shape

(10, 32)

In [83]:
#Train the model
for epoch in range(num_epochs):
    # batch_index, (example_data, example_targets)
    # labels is a tensor of shape (batch_size,) that contains the true labels for a batch of images.
    # images.shape = torch.Size([128, 1, 28, 28])
    for i, (images, labels) in enumerate(train_loader):
        #flatten the images:
        images = images.reshape(-1, input_size).T #turn into a vector
        labels = labels.numpy() # converting the labels tensor from a PyTorch tensor object to a numpy array.

        #convert labels to one-hot vectors
        y = np.zeros((num_classes, batch_size))
        batch_size_i = labels.shape[0]
        y[labels, np.arange(batch_size_i)] = 1 #last batch of batch_size = 128 is 96
        if batch_size_i < batch_size:
            y = np.delete(y, np.arange(batch_size_i, batch_size), axis = 1) #delete the remaining unsed columns
        x, y = torch.tensor(images), torch.tensor(y) #convert 'images' and 'y' into PyTorch tensors.

        #forward pass 
        a1, a2, y_hat = forward(x)

        #compute the loss
        loss = -torch.sum(y * torch.log(y_hat))

        #backward pass
        delta3 = (y_hat - y).float() #change from double to float 
        delta2 = torch.matmul(W3.T, delta3)* a2 * (1- a2)
        delta1 = torch.matmul(W2.T, delta2) * a1 * (1- a1)

        dW3 = torch.matmul(delta3, a2.T) #(y_hat - y)a2^T
        dW2 = torch.matmul(delta2, a1.T) # W3.T(y_hat - y)a2(1- a2)a1.T
        dw1 = torch.matmul(delta1, x.T) # W2.T*delta2*a1*(1- a1)x.T

        #update weights using SGD  
        W1 -= learning_rate* dw1 / batch_size
        W2 -= learning_rate* dW2 / batch_size
        W3 -= learning_rate * dW3 / batch_size
        

C:\Users\thong\AppData\Local\Temp\ipykernel_19000\3774397082.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x, y = torch.tensor(images), torch.tensor(y) #convert 'images' and 'y' into PyTorch tensors.


In [84]:
#code for understanding syntax
labels

array([3, 7, 0, 3, 7, 4, 2, 6, 7, 5, 8, 7, 9, 6, 0, 1, 7, 7, 7, 5, 8, 1,
       6, 1, 1, 1, 2, 8, 7, 8, 8, 9], dtype=int64)

In [85]:
#code for understanding syntax
np.arange(batch_size_i)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [86]:
#code for understanding syntax
test0 = np.zeros((num_classes, batch_size))
test0 #10 x 128

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [87]:
#code for understanding syntax
test0[labels, np.arange(batch_size_i)] = 1 #set test0[label[i], i] = 1
test0

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [88]:
correct = 0
total = 0 
test_losses = []

# is a context manager that temporarily disables gradient computation during model inference. 
# reduce memory consumption and computation time since gradients are not needed for inference.
# is used to compute test accuracy and loss during the testing phase.
# when you are sure that you will not call Tensor.backward() 
with torch.no_grad():
    for images, labels in test_loader:
        #Flatten the images
        images = images.reshape(-1, input_size).T
        labels = labels.numpy()

        #convert labels into one-hot vectors
        y = np.zeros((num_classes, batch_size))
        batch_size_j = labels.shape[0]
        y[labels,np.arange(batch_size_j)] = 1
        if batch_size_j < batch_size:
            y = np.delete(y, np.arange(batch_size_j, batch_size), axis = 1)
        
        x, y = torch.tensor(images), torch.tensor(y)

        #forward pass
        _, _, y_hat = forward(x)

        # compute loss
        #This function returns the index of the maximum value in each column of the one-hot encoded y tensor.
        #The dim=0 argument specifies that the function should return the index along the first dimension of the tensor, which corresponds to the batch size.
        test_loss = criterion(y_hat, torch.argmax(y, dim = 0))
        test_losses.append(test_loss.item())

        #compute predictions and accuracy 
        # predictions is a tensor of shape (1, batch_size). 
        # Each element in this tensor represents the predicted class label for the corresponding input image in the batch
        #torch.max() is used to get the index of the maximum value in the tensor y_hat along the 0-th dimension
        
        _, predictions = torch.max(y_hat, 0)

        predictions = np.array(predictions)
        labels = np.array(labels)

        total += y.size(1)
        correct += (predictions == labels).sum().item()     

C:\Users\thong\AppData\Local\Temp\ipykernel_19000\781778586.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x, y = torch.tensor(images), torch.tensor(y)


In [89]:
#first dimension = 10 = batch_test_size ->dim = 0 
y

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)

In [90]:
#dim 1 x 10, (batch_size,)
torch.argmax(y, dim = 0)

tensor([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [91]:
#dim 10 x 10, (num_classes, batch_size)
y_hat

tensor([[4.7950e-06, 1.0077e-03, 1.6188e-04, 8.2712e-01, 3.1803e-07, 1.4093e-05,
         2.7877e-04, 2.2274e-06, 3.6304e-03, 1.2768e-03],
        [1.0209e-04, 2.8491e-05, 1.1066e-06, 1.3787e-07, 9.7752e-01, 8.7183e-05,
         4.6971e-05, 4.5300e-05, 4.1221e-03, 2.8811e-07],
        [3.6985e-04, 5.2429e-03, 8.3877e-05, 1.3700e-04, 1.1577e-02, 9.9244e-01,
         2.8962e-03, 8.1360e-05, 2.2597e-03, 5.4735e-03],
        [2.3064e-03, 1.5788e-01, 4.5831e-05, 3.2359e-04, 1.9485e-03, 5.6665e-03,
         9.9569e-01, 1.2401e-04, 6.1460e-03, 7.8874e-07],
        [1.2725e-05, 5.1942e-06, 5.0506e-01, 3.4314e-06, 2.3034e-05, 1.9848e-07,
         1.4108e-08, 7.4706e-01, 7.9489e-03, 3.8632e-04],
        [4.2034e-05, 2.1159e-02, 2.0766e-03, 1.6933e-01, 4.0312e-04, 1.2286e-05,
         5.6625e-04, 2.7190e-03, 7.5546e-01, 2.5710e-04],
        [2.8408e-08, 2.0737e-06, 4.2517e-04, 2.5782e-04, 4.3001e-04, 2.2009e-05,
         1.1695e-07, 4.5659e-04, 2.0575e-02, 9.9252e-01],
        [9.6345e-01, 5.9457

In [92]:
criterion(y_hat, torch.argmax(y, dim = 0)).item() #item() for getting the value

2.4444947242736816

In [93]:
# Print test accuracy and loss
test_accuracy = 100 * correct / total
test_loss = np.mean(test_losses)
print(test_accuracy, test_loss)

89.7 2.274928773999214


# Simple Neural Network (but with auto-grad)

In [112]:
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms 

In [113]:
class Net(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2, num_classes):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size1)
        self.fc2 = nn.Linear(hidden_size1, hidden_size2)
        self.fc3 = nn.Linear(hidden_size2, num_classes)

    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        x = F.softmax(self.fc3(x), dim = 1)
        return x


In [117]:
#initialize the model, loss function, and optimizer
model = Net(input_size= 784, hidden_size1= 300, hidden_size2 = 200, num_classes = 10)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr = 0.07)

In [118]:
#train model
accuracy_list = []
num_epochs = 20
for epoch in range(num_epochs):
    ##new## 
    correct = 0
    total = 0
    ####
    for i, (images, labels) in enumerate(train_loader):
        #flatten the images
        images = images.reshape(-1, input_size)

        #forward pass 
        outputs = model(images)
        # _, predicted = torch.max(outputs.data, 1)
        loss = criterion(outputs, labels)

        #backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    #evaluate the model
    with torch.no_grad():
        correct = 0 
        total = 0
        for images, labels in test_loader:
            images = images.reshape(-1, input_size)
            outputs = model(images)
            _, predicted = torch.max(outputs.data,1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        accuracy = 100 * correct / total
        print(f"Epoch {epoch + 1}/{num_epochs}, Accuracy: {accuracy:.2f}%")
        

Epoch 1/20, Accuracy: 11.35%
Epoch 2/20, Accuracy: 20.98%
Epoch 3/20, Accuracy: 34.46%
Epoch 4/20, Accuracy: 41.57%
Epoch 5/20, Accuracy: 52.15%
Epoch 6/20, Accuracy: 60.50%
Epoch 7/20, Accuracy: 63.81%
Epoch 8/20, Accuracy: 65.27%
Epoch 9/20, Accuracy: 65.95%
Epoch 10/20, Accuracy: 66.24%
Epoch 11/20, Accuracy: 66.58%
Epoch 12/20, Accuracy: 71.79%
Epoch 13/20, Accuracy: 73.02%
Epoch 14/20, Accuracy: 73.70%
Epoch 15/20, Accuracy: 74.34%
Epoch 16/20, Accuracy: 74.84%
Epoch 17/20, Accuracy: 75.09%
Epoch 18/20, Accuracy: 75.24%
Epoch 19/20, Accuracy: 75.52%
Epoch 20/20, Accuracy: 75.57%


In [116]:
# num epoch = 25, lr = 0.15, batch_size = 64, accuracy:76.03
# num epoch = 25, lr = 0.1, batch_size = 64, accuracy:74.89
# num epoch = 20, lr = 0.08, batch_size = 64, accuracy: 66.54
# num epoch = 20, lr = 0.15, batch_size = 32, accuracy: 
# num epoch = 20, lr = 0.1, batch_size = 32, accuracy: 
# num epoch = 20, lr = 0.07, batch_size = 32, accuracy: 75.57
# num epoch = 20, lr = 0.06, batch_size = 32, accuracy:
# num epoch = 25, lr = 0.15, batch_size = 32, accuracy: 
# num epoch = 25, lr = 0.1, batch_size = 32, accuracy: 76.56
# num epoch = 25, lr = 0.08, batch_size = 32, accuracy:
# num epoch = 25, lr = 0.05, batch_size = 32, accuracy:
# num epoch = 30, lr = 0.1, batch_size = 32, accuracy: 
# num epoch = 30, lr = 0.08, batch_size = 32, accuracy:
accuracy

76.56